@startuml

class Main {
}
interface Print {
    +{abstract} printWeak()
    +{abstract} printStrong()
}
class PrintBanner {
    +printWeak()
    +printStrong()
}
class Banner {
    +showWithParen()
    +showWithAster()
}

Main --> Print
Print <|. PrintBanner
PrintBanner -|> Banner

@enduml